# Configuração do Banco de Dados (Supabase - PostgreSQL)
# Note o "jdbc:" adicionado no início da URL, que é obrigatório para o Spring Boot
spring.datasource.url=jdbc:postgresql://db.jkojnvsekthxiylujlup.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Z9!9c2J02Yy^#78J12u!

# Configuração do Hibernate (JPA)
# "update" cria ou atualiza as tabelas automaticamente com base nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configuração do JWT
jwt.secret=uma-chave-secreta-muito-longa-e-segura-para-assinatura-do-token-jwt-que-deve-ter-pelo-menos-256-bits
jwt.expiration=86400000